name: Model Monitoring

on:
  schedule:
    - cron: "0 8 * * *"  # ogni giorno alle 8
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    # QUESTA È LA PARTE CHE RISOLVE L'ERRORE 403 OVVERO IN PERMESSI: IL BOT AVEVA PERMESSI SOLO DI LETTURA
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring
        run: python monitoring/monitor.py

      - name: Trigger alert if needed
        run: python monitoring/alert.py

      - name: Commit metrics
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "monitor-bot"
          git add monitoring/metrics.csv
          # Aggiunto '|| echo ...' per non far fallire lo step se non ci sono modifiche
          git commit -m "Monitoring update" || echo "No changes to commit"
          git push
